### PR TITLE
Added 3d-tic-tac-toe game

### PR DESCRIPTION
**Pull request by pranjay-poddar**
Added Tic Tac Toe Game with 3d UI, animations, and sound effects in JS

linked issue 
#45

### CODE REVIEW

**Review by geekymeeky — CHANGES_REQUESTED** [review]
There's already a tic-tac-toe game present. Kindly replace that with this modified version.

**Comment by pranjay-poddar** [comment]
I request you to please check it once it is an enhanced version of tic tac toe with better and responsive UI and i've started working on it only  after your approval on issue no. #45

**Comment by kanishkaa24** [comment]
Looks great

**Review by kanishkaa24 — APPROVED** [review]

**Review by geekymeeky — APPROVED** [review]
@pranjay-poddar Excellent work

**Comment by pranjay-poddar** [comment]
Thank you!✨

**Pull request merged**
