### PR TITLE
Added tetris files

### PR DESCRIPTION
**Pull request by Adarsh88**
#35 I've completed the game, please check the PR!

### CODE REVIEW

**Comment by kanishkaa24** [comment]
Changes that need to be addressed:
- Remove the internal CSS and add it in an external CSS file.
- Add a navigation in your game to the home page of the main website.

**Review by kanishkaa24 — CHANGES_REQUESTED** [review]
Changes that need to be addressed:

Remove the internal CSS and add it in an external CSS file.
Add a navigation in your game to the home page of the main website.

**Comment by Adarsh88** [comment]
I've done it, please check it now

**Comment by Adarsh88** [comment]
I've done it, please check it now @kanishkaa24 .

**Review by kanishkaa24 — APPROVED** [review]

**Review by geekymeeky — APPROVED** [review]

**Pull request merged**
