### PR TITLE
dot-and-boxes-added

### LINKED ISSUE #52: Adding new game known as DOT and BOXES
This is a very interesting game. I still play it using pen paper.
If you don't know about this game [click here](https://en.wikipedia.org/wiki/Dots_and_Boxes).
I would like to work on this game, please assign me this under DCP'21.

### PR DESCRIPTION
**Pull request by sumitvajarinkar**
Closes #52

### CODE REVIEW

**Comment by kanishkaa24** [comment]
How can one play this game?

**Comment by sumitvajarinkar** [comment]
> How can one play this game?

If its your turn then you have to just join 2 dots by clicking between them.
And if the 4th side of box is closes by your line then your score will be increment. Although Other  side closes by Computer.

Hope you'll get it.

**Comment by geekymeeky** [comment]
> > How can one play this game?
> 
> If its your turn then you have to just join 2 dots by clicking between them.
> And if the 4th side of box is closes by your line then your score will be increment. Although Other side closes by Computer.
> 
> Hope you'll get it.

Can you please demonstrate the gameplay since I couldn't find a way to connect the dots?

**Comment by sumitvajarinkar** [comment]
> > > How can one play this game?
> > 
> > 
> > If its your turn then you have to just join 2 dots by clicking between them.
> > And if the 4th side of box is closes by your line then your score will be increment. Although Other side closes by Computer.
> > Hope you'll get it.
> 
> Can you please demonstrate the gameplay since I couldn't find a way to connect the dots?

I deployed it on github here it is https://sumitvajarinkar.github.io/dotAndBoxes_Game/

Can I attach video?

**Comment by sumitvajarinkar** [comment]
> > > > How can one play this game?
> > > 
> > > 
> > > If its your turn then you have to just join 2 dots by clicking between them.
> > > And if the 4th side of box is closes by your line then your score will be increment. Although Other side closes by Computer.
> > > Hope you'll get it.
> > 
> > 
> > Can you please demonstrate the gameplay since I couldn't find a way to connect the dots?
> 
> I deployed it on Github here it is https://sumitvajarinkar.github.io/dotAndBoxes_Game/
>I will try to fix it.

**Pull request closed without merging**
