### PR TITLE
Created whole tic tac toe game

### PR DESCRIPTION
**Pull request by aradhana72**
Added new html css and js files.The game is absolutely correct and working.Please go through it and look if further updates are needed.

### CODE REVIEW

**Comment by geekymeeky** [comment]
Please don't alter the index page. Add a new page for the tic-tac-toe game and embed your game in it as done in the rock-paper-scissor game.

**Comment by aradhana72** [comment]
Okay sure

**Comment by geekymeeky** [comment]
image
The output doesn't seem right. Please review your changes.

**Comment by aradhana72** [comment]
Now its working,please review.

**Comment by aradhana72** [comment]
Awesome, thanks!

**Pull request merged**
