### PR TITLE
Flip me game 

### PR DESCRIPTION
**Pull request by Naman-mahi**
I flip me game create you see it and close (#96 ) this issue 
**Live**👇
https://naman-mahi.github.io/todaytask/

### CODE REVIEW

**Review by geekymeeky — CHANGES_REQUESTED** [review]
- Kindly add a button to navigate to the home page.

**Comment by Naman-mahi** [comment]
> * Kindly add a button to navigate to the home page.

Done sir added Button

**Review by kanishkaa24 — CHANGES_REQUESTED** [review]
Your game is not visible on the main webpage of JS Games. Replace the file in index.html as this was an enhancement.

**Comment by Naman-mahi** [comment]
> Your game is not visible on the main webpage of JS Games. Replace the file in index.html as this was an enhancement.

But there is already index.html file

**Comment by kanishkaa24** [comment]
> > Your game is not visible on the main webpage of JS Games. Replace the file in index.html as this was an enhancement.
> 
> But there is already index.html file

I mean update the source link of your HTML file in the index.html.

**Comment by Naman-mahi** [comment]
Okay

**Comment by Naman-mahi** [comment]
> > > Your game is not visible on the main webpage of JS Games. Replace the file in index.html as this was an enhancement.
> > 
> > 
> > But there is already index.html file
> 
> I mean update the source link of your HTML file in the index.html.

Done @kanishkaa24 I edit index page and image also uploaded

**Review by kanishkaa24 — CHANGES_REQUESTED** [review]
Your CSS and JS files are not currently linked to your game's HTML file.

**Comment by Naman-mahi** [comment]
I'll check and fix it sir 

> Your CSS and JS files are not currently linked to your game's HTML file.

I'll check and fix it sir

**Comment by Naman-mahi** [comment]
> I'll check and fix it sir
> 
> > Your CSS and JS files are not currently linked to your game's HTML file.
> 
> I'll check and fix it sir



> Your CSS and JS files are not currently linked to your game's HTML file.

sir now ist working .

**Review by kanishkaa24 — CHANGES_REQUESTED** [review]
- Fix merge conflicts
- Add your name as an enhancement to the existing flip me game. Replace the existing flip me game. DO NOT create a new game.

**Comment by Naman-mahi** [comment]
> * Fix merge conflicts
> * Add your name as an enhancement to the existing flip me game. Replace the existing flip me game. DO NOT create a new game.

Okay

**Comment by Naman-mahi** [comment]
> * Fix merge conflicts
> * Add your name as an enhancement to the existing flip me game. Replace the existing flip me game. DO NOT create a new game.

I updated old flip-me game. Sir now you can check my PR and merge it.

**Review by kanishkaa24 — APPROVED** [review]

**Review by geekymeeky — APPROVED** [review]

**Pull request merged**
